services:
  - type: web
    name: lifelink-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # You can override these in the Render Dashboard later!
      - key: APP_ENV
        value: production
      - key: USE_MOCK_APIS
        value: "True"
      - key: AGORA_APP_ID
        value: c02d1ae0967e47bbaa6fcece4b81acf6
      - key: AGORA_APP_CERTIFICATE
        value: d8737e96677e4ad3821e10bb3fd98efb
